# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SgRipper < Formula
  desc "AWS Security Group and ENI cleaner.."
  homepage "https://github.com/cloud-crafts/sg-ripper"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.1.2/sg-ripper-0.1.2-darwin-arm64.tar.gz"
      sha256 "a5dbbc095b8aa065862ac5bbbb7ef2f435593d4c40b385f9a3513f5d6b2ffb44"

      def install
        bin.install "bin/sg-ripper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.1.2/sg-ripper-0.1.2-darwin-amd64.tar.gz"
      sha256 "3ca2a8948bb20cb16f53c27bf9bff260f6f57723faffbedd277fa1d925888d9b"

      def install
        bin.install "bin/sg-ripper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.1.2/sg-ripper-0.1.2-linux-amd64.tar.gz"
      sha256 "12876f4b6ea411537589b1b12cb6da3d78d148204729a11823de2a6f6bb246ae"

      def install
        bin.install "bin/sg-ripper"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.1.2/sg-ripper-0.1.2-linux-armv6.tar.gz"
      sha256 "7a68b14504f3829aa53938d31363d0128c449c7b528388440034db87d360bf0a"

      def install
        bin.install "bin/sg-ripper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.1.2/sg-ripper-0.1.2-linux-arm64.tar.gz"
      sha256 "0add9a974c919aabe70655ae71fd77ac5e8f36ac8f5a9b233776431efec4e93d"

      def install
        bin.install "bin/sg-ripper"
      end
    end
  end

  test do
    system "#{bin}/sg-ripper", "--help"
  end
end
