# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SgRipper < Formula
  desc "AWS Security Group and ENI cleaner."
  homepage "https://github.com/cloud-crafts/sg-ripper"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.2.1/sg-ripper-0.2.1-darwin-amd64.tar.gz"
      sha256 "8779e183c6972b9323ad246d2a71a9ba2dd6bb6560e4fee40e2f6d7c32753eee"

      def install
        bin.install "bin/sg-ripper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.2.1/sg-ripper-0.2.1-darwin-arm64.tar.gz"
      sha256 "668cef5fe584627a494f10bfa5e29c14afd5047c88558600ad339c7851d7ec21"

      def install
        bin.install "bin/sg-ripper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.2.1/sg-ripper-0.2.1-linux-armv6.tar.gz"
      sha256 "585164b639c7237aec448f3167b649e16bd615ccf227f93b755c193ad07ff065"

      def install
        bin.install "bin/sg-ripper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.2.1/sg-ripper-0.2.1-linux-amd64.tar.gz"
      sha256 "eda8f47bb3657ddba9d141d0b0b96aafb992b49e3d080c6bdfc26d686e330c18"

      def install
        bin.install "bin/sg-ripper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloud-crafts/sg-ripper/releases/download/v0.2.1/sg-ripper-0.2.1-linux-arm64.tar.gz"
      sha256 "fbe69e2ed3fc951c361e09bd76a0e0019939674ac06438a7cb426cee49bcb583"

      def install
        bin.install "bin/sg-ripper"
      end
    end
  end

  test do
    system "#{bin}/sg-ripper", "--help"
  end
end
